[package]
name = "download"
version = "0.3.1"
edition = "2018"
authors = ["thin-edge.io team <info@thin-edge.io>"]
license = "Apache-2.0"
description = "download_manager"


[dependencies]
backoff = { version = "0.3", features = ["tokio"] }
json_sm = { path = "../json_sm" }
log = "0.4"
mqtt_client = { path = "../../common/mqtt_client" }
reqwest = "0.11"
tedge_utils = { path = "../../common/tedge_utils" }
tempfile = "3.2"
thiserror = "1.0"
tokio = "1.9"
url = "2.2"

[dev-dependencies]
regex = "1.5"
tokio = "1.9"
tokio-test = "0.4"
