[package]
name = "c8y_translator"
version = "0.7.2"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.58.1"

[dependencies]
clock = { path = "../../common/clock" }
json-writer = { path = "../../common/json_writer" }
serde_json = "1.0"
thin_edge_json = { path = "../thin_edge_json" }
thiserror = "1.0"
time = "0.3"

[dev-dependencies]
anyhow = "1.0"
assert_matches = "1.5"
assert-json-diff = "2.0"
criterion = "0.3"
pretty_assertions = "1.0"
proptest = "1.0"
serde_json = "1.0"
test-case = "2.0"
time = { version = "0.3", features = ["macros"] }

[features]
# use: #[cfg(feature="integration-test")]
integration-test = []

[[bench]]
name = "thin_edge_json"
harness = false
