[package]
name = "tedge_config"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[features]
default = []
test = []
cryptoki = ["certificate/cryptoki"]

[dependencies]
anyhow = { workspace = true }
camino = { workspace = true, features = ["serde", "serde1"] }
certificate = { workspace = true, features = ["reqwest"] }
clap = { workspace = true }
clap_complete = { workspace = true }
doku = { workspace = true }
figment = { workspace = true, features = ["env", "toml"] }
humantime = { workspace = true }
mqtt_channel = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true, features = ["rustls-tls-native-roots"] }
rustls = { workspace = true }
serde = { workspace = true, features = ["rc"] }
serde_ignored = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tedge_config_macros = { workspace = true }
tedge_utils = { workspace = true, features = ["timestamp"] }
thiserror = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
which = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
figment = { workspace = true, features = ["test"] }
serde_json = { workspace = true }
tedge_test_utils = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }

[lints]
workspace = true
