[package]
name = "tedge_config"
version = "0.7.1"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.58.1"

[dependencies]
certificate = { path = "../certificate" }
serde = { version = "1.0", features = ["derive"] }
tedge_utils = { path = "../tedge_utils" }
tedge_users = { path = "../tedge_users" }
tempfile = "3.2"
thiserror = "1.0"
toml = "0.5"
url = "2.2"

[dev-dependencies]
assert_matches = "1.5"
tedge_test_utils = { path = "../../tests/tedge_test_utils" }
