[package]
name = "tedge_config"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
camino = { workspace = true, features = ["serde", "serde1"] }
certificate = { workspace = true }
doku = { workspace = true }
figment = { workspace = true, features = ["env", "toml"] }
mqtt_channel = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true, features = ["rc"] }
serde_ignored = { workspace = true }
strum_macros = { workspace = true }
tedge_config_macros = { workspace = true }
tedge_utils = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
assert_matches = { workspace = true }
figment = { workspace = true, features = ["test"] }
tedge_test_utils = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }
