[package]
name = "tedge_config"
version = "0.8.1"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.58.1"

[dependencies]
certificate = { path = "../certificate" }
serde = { version = "1.0", features = ["derive"] }
strum_macros = { version = "0.24", optional = true }
tedge_utils = { path = "../tedge_utils", features = ["tedge-derive"] }
tempfile = "3.2"
thiserror = "1.0"
toml = "0.5"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = [ "time" ] }
url = "2.2"

[dev-dependencies]
anyhow = "1.0"
assert_matches = "1.5"
tedge_test_utils = { path = "../../tests/tedge_test_utils" }
test-case = "2.2"
