[package]
name = "collectd_ext"
description = "thin-edge extension adding support for collectd"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
batcher = { workspace = true }
clock = { workspace = true }
log = { workspace = true }
tedge_actors = { workspace = true }
tedge_api = { workspace = true }
tedge_mqtt_ext = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, features = ["sync", "time"] }

[dev-dependencies]
anyhow = { workspace = true }
assert_matches = { workspace = true }
time = { workspace = true, features = ["macros"] }

[lints]
workspace = true
