[package]
name = "tedge"
description = "tedge is the cli tool for thin-edge.io"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = "README.md"
default-run = "tedge"

[dependencies]
anstyle = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
c8y-firmware-plugin = { workspace = true }
c8y-remote-access-plugin = { workspace = true }
c8y_api = { workspace = true }
camino = { workspace = true }
cap = { workspace = true }
certificate = { workspace = true }
clap = { workspace = true }
clap_complete = { version = "4.5.42", features = ["unstable-dynamic"] }
doku = { workspace = true }
humantime = { workspace = true }
hyper = { workspace = true, default-features = false }
mime_guess = { workspace = true }
mqtt_channel = { workspace = true }
nix = { workspace = true }
pad = { workspace = true }
pem = { workspace = true }
rasn = { workspace = true }
rasn-cms = { workspace = true }
reqwest = { workspace = true, features = [
    "json",
    "multipart",
    "rustls-tls-native-roots",
    "stream",
] }
rpassword = { workspace = true }
rumqttc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum_macros = { workspace = true }
tedge-agent = { workspace = true }
tedge-apt-plugin = { workspace = true }
tedge-mapper = { workspace = true }
tedge-watchdog = { workspace = true }
tedge-write = { workspace = true }
tedge_api = { workspace = true }
tedge_config = { workspace = true }
tedge_utils = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
toml = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
which = { workspace = true }
yansi = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
assert_matches = { workspace = true }
mockall = { workspace = true }
mockito = { workspace = true }
mqtt_tests = { workspace = true }
predicates = { workspace = true }
rcgen = { workspace = true }
tedge_test_utils = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }
tokio = { workspace = true }
x509-parser = { workspace = true }


[features]
integration-test = []

[lints]
workspace = true
