[package]
name = "tedge"
description = "tedge is the cli tool for thin-edge.io"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = "README.md"

[package.metadata.deb]
recommends = "mosquitto"
maintainer-scripts = "../../../configuration/debian/tedge"

[dependencies]
anyhow = "1.0"
atty = "0.2"
base64 = "0.13"
camino = "1.1.4"
certificate = { path = "../../common/certificate" }
clap = { version = "3", features = ["cargo", "derive"] }
doku = "0.21"
hyper = { version = "0.14", default-features = false }
pad = "0.1"
reqwest = { version = "0.11", default-features = false, features = [
    "blocking",
    "json",
    "rustls-tls-native-roots",
    "stream",
] }
rpassword = "5.0"
rumqttc = "0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum_macros = "0.24.1"
tedge_config = { path = "../../common/tedge_config" }
tedge_utils = { path = "../../common/tedge_utils" }
thiserror = "1.0"
toml = "0.5"
tracing = { version = "0.1", features = ["attributes", "log"] }
url = "2.2"
which = "4.2"
yansi = "0.5"

[dev-dependencies]
assert_cmd = "2.0"
assert_matches = "1.5"
mockito = "0.31"
mqtt_tests = { path = "../../tests/mqtt_tests" }
pem = "1.0"
predicates = "2.1"
tempfile = "3.2"
test-case = "2.2"
tokio = { version = "1.23" }

[features]
integration-test = []
