[package]
name = "tedge"
description = "tedge is the cli tool for thin-edge.io"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = "README.md"

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
camino = { workspace = true }
certificate = { workspace = true }
clap = { workspace = true, features = ["cargo", "derive"] }
doku = { workspace = true }
hyper = { workspace = true, default-features = false }
pad = { workspace = true }
reqwest = { workspace = true, features = [
    "blocking",
    "json",
    "rustls-tls-native-roots",
    "stream",
] }
rpassword = { workspace = true }
rumqttc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum_macros = { workspace = true }
tedge_config = { workspace = true }
tedge_utils = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
which = { workspace = true }
yansi = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
assert_matches = { workspace = true }
mockito = { workspace = true }
mqtt_tests = { workspace = true }
pem = { workspace = true }
predicates = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }
tokio = { workspace = true }

[features]
integration-test = []
