[package]
name = "tedge"
version = "0.5.1"
edition = "2018"
authors = ["thin-edge.io team <info@thin-edge.io>"]
license = "Apache-2.0"
readme = "README.md"
description = "tedge is the cli tool for thin-edge.io"

[package.metadata.deb]
depends = "mosquitto"
maintainer-scripts = "../../../configuration/debian/tedge"

[dependencies]
anyhow = "1.0"
base64 = "0.13"
certificate = { path = "../../common/certificate" }
chrono = "0.4"
futures = "0.3"
hyper = { version = "0.14", default-features = false }
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls", "stream"] }
rpassword = "5.0"
rumqttc = "0.10"
rustls = "0.20.2"
rustls_0_19 = {package = "rustls", version = "0.19.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
tedge_config = { path = "../../common/tedge_config" }
tedge_users = { path = "../../common/tedge_users" }
tedge_utils = { path = "../../common/tedge_utils" }
thiserror = "1.0"
toml = "0.5"
url = "2.2"
which = "4.2"

[dev-dependencies]
assert_cmd = "2.0"
assert_matches = "1.5"
mockito = "0.30"
pem = "1.0"
predicates = "2.0"
tempfile = "3.2"
test-case = "1.2"

[features]
integration-test = []
mosquitto-available = []      # Enable tests requesting mosquitto installed
root-access = []              # Enable tests requesting root access
tedge-user = []               # Enable tests requesting a tedge user
openrc = []                   # Enable usage of OpenRC
