[package]
name = "tedge_users"
version = "0.5.1"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.58"

[dependencies]
thiserror = "1.0"

[target.'cfg(unix)'.dependencies]
users = "0.11"
