[package]
name = "flockfile"
version = "0.7.3"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.58.1"

[dependencies]
thiserror = "1.0"

[target.'cfg(unix)'.dependencies]
nix = "0.24"
tracing = { version = "0.1", features = ["log"] }

[dev-dependencies]
assert_matches = "1.5"
tempfile = "3.2"
