[package]
name = "plugin_sm"
version = "0.8.1"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.58.1"

[dependencies]
async-trait = "0.1"
csv = "1.1"
download = { path = "../../common/download" }
logged_command = { path = "../../common/logged_command" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tedge_api = { path = "../tedge_api" }
time = { version = "0.3", features = ["formatting"] }
thiserror = "1.0"
tokio = { version = "1.8", features = ["process", "rt"] }
tracing = { version = "0.1", features = ["attributes", "log"] }
url = "2.2"

[dev-dependencies]
anyhow = "1.0"
assert_matches = "1.5"
serial_test = "0.8"
tempfile = "3.2"
test-case = "2.2"

