[package]
name = "plugin_sm"
version = "0.6.3"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.58.1"

[dependencies]
agent_interface = { path = "../agent_interface" }
async-trait = "0.1"
csv = "1.1"
download = { path = "../../common/download" }
logged_command = { path = "../../common/logged_command" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.8", features = ["process", "rt"] }
tracing = { version = "0.1", features = ["attributes", "log"] }
url = "2.2"

[dev-dependencies]
anyhow = "1.0"
serial_test = "0.5.1"
tempfile = "3.2"
test-case = "2.0"

