[package]
name = "tedge-p11-server"
description = "thin-edge PKCS#11 server"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
asn1-rs.workspace = true
camino.features = ["serde1"]
camino.workspace = true
clap.workspace = true
cryptoki.workspace = true
pem.workspace = true
percent-encoding.workspace = true
postcard.workspace = true
rand.workspace = true
rsa.workspace = true
rustls.workspace = true
sd-listen-fds.workspace = true
serde.workspace = true
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "net",
] }
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
yansi.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
