# yaml-language-server: $schema=https://nfpm.goreleaser.com/static/schema.json
---
name: c8y-configuration-plugin
description: |
  thin-edge.io device configuration management for Cumulocity
arch: "${PKG_ARCH}"
platform: "linux"
version: "${GIT_SEMVER}"
release: "${RELEASE}"
section: misc
priority: "optional"
maintainer: "thin-edge.io team <info@thin-edge.io>"
vendor: "thin-edge.io"
homepage: "https://thin-edge.io"
license: "Apache-2.0"

replaces:
  - c8y_configuration_plugin
conflicts:
  - c8y_configuration_plugin (<= 0.8.1)

deb:
  fields:
    Vcs-Browser: ${CI_PROJECT_URL}
    Vcs-Git: ${CI_PROJECT_URL}
  compression: xz
  breaks:
    - c8y_configuration_plugin (<= 0.8.1)

contents:
  # service definitions
  - src: ./configuration/init/systemd/c8y-configuration-plugin.service
    dst: /lib/systemd/system/
    file_info:
      mode: 0644
    packager: deb

  - src: ./configuration/init/systemd/c8y-configuration-plugin.service
    dst: /lib/systemd/system/
    file_info:
      mode: 0644
    packager: rpm

  # Symlink for backwards compatibility
  # Deprecate: Remove symlink in 1.x release
  - src: /usr/bin/c8y-configuration-plugin
    dst: /usr/bin/c8y_configuration_plugin
    type: symlink

overrides:
  apk:
    scripts:
      preinstall: configuration/package_scripts/_generated/c8y-configuration-plugin/apk/preinst
      postinstall: configuration/package_scripts/_generated/c8y-configuration-plugin/apk/postinst
      preremove: configuration/package_scripts/_generated/c8y-configuration-plugin/apk/prerm
      postremove: configuration/package_scripts/_generated/c8y-configuration-plugin/apk/postrm

  rpm:
    scripts:
      preinstall: configuration/package_scripts/_generated/c8y-configuration-plugin/rpm/preinst
      postinstall: configuration/package_scripts/_generated/c8y-configuration-plugin/rpm/postinst
      preremove: configuration/package_scripts/_generated/c8y-configuration-plugin/rpm/prerm
      postremove: configuration/package_scripts/_generated/c8y-configuration-plugin/rpm/postrm

  deb:
    scripts:
      preinstall: configuration/package_scripts/_generated/c8y-configuration-plugin/deb/preinst
      postinstall: configuration/package_scripts/_generated/c8y-configuration-plugin/deb/postinst
      preremove: configuration/package_scripts/_generated/c8y-configuration-plugin/deb/prerm
      postremove: configuration/package_scripts/_generated/c8y-configuration-plugin/deb/postrm
