[package]
name = "flockfile"
version = "0.2.0"
authors = ["Software AG <thin-edge-team@softwareag.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"

[target.'cfg(unix)'.dependencies]
log = "0.4"
nix = "0.20"

[dev-dependencies]
assert_matches = "1.5"
tempfile = "3.2"
