[package]
name = "tedge_downloader_ext"
description = "thin-edge extension adding downloaders"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = { workspace = true }
camino = { workspace = true }
certificate = { workspace = true, features = ["reqwest"] }
download = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
tedge_actors = { workspace = true }
tedge_utils = { workspace = true }

[dev-dependencies]
mockito = { workspace = true }
tedge_test_utils = { workspace = true }
tokio = { workspace = true, default_features = false, features = ["time"] }
uzers = { workspace = true }
whoami = { workspace = true }

[lints]
workspace = true
