[package]
name = "tedge_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.52"
thiserror = "1.0.30"
tokio = { version = "1.16.1", features = ["sync"] }
toml = "0.5.8"

[dev-dependencies]
static_assertions = "1.1.0"
tokio = { version = "1.16.1", features = ["full"] }
