[package]
name = "tedge_api"
version = "0.8.1"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.63"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clock = { path = "../../common/clock" }
csv = "1.1"
download = { path = "../../common/download" }
json-writer = { path = "../../common/json_writer" }
mqtt_channel = { path = "../../common/mqtt_channel" }
nanoid = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
time = { version = "0.3", features = ["formatting", "local-offset", "parsing", "serde", "serde-well-known"] }

[dev-dependencies]
anyhow = "1.0"
assert_matches = "1.5"
clock = { path = "../../common/clock" }
criterion = "0.3"
mockall = "0.11"
proptest = "1.0"
regex = "1.5"
stats_alloc = "0.1"
test-case = "2.2"
time = { version = "0.3", features = ["macros"] }
walkdir = "2"

