[package]
name = "tedge_api"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = "0.1"
clock = { path = "../../common/clock" }
csv = "1.1"
download = { path = "../../common/download" }
json-writer = { path = "../../common/json_writer" }
mqtt_channel = { path = "../../common/mqtt_channel" }
nanoid = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
time = { version = "0.3", features = [
    "formatting",
    "local-offset",
    "parsing",
    "serde",
    "serde-well-known",
] }
tracing = { version = "0.1", features = ["attributes", "log"] }

[dev-dependencies]
anyhow = "1.0.6"
assert_matches = "1.5"
clock = { path = "../../common/clock" }
criterion = "0.3"
maplit = "1.0.2"
mockall = "0.11"
proptest = "1.0"
regex = "1.5"
stats_alloc = "0.1"
test-case = "2.2"
time = { version = "0.3", features = ["macros"] }
walkdir = "2"
