[package]
name = "tedge_api"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
camino = { workspace = true }
clock = { workspace = true }
csv = { workspace = true }
download = { workspace = true }
json-writer = { workspace = true }
log = { workspace = true }
mqtt_channel = { workspace = true }
nanoid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = [
    "formatting",
    "local-offset",
    "parsing",
    "serde",
    "serde-well-known",
] }

[dev-dependencies]
anyhow = { workspace = true }
assert_matches = { workspace = true }
clock = { workspace = true }
maplit = { workspace = true }
mockall = { workspace = true }
regex = { workspace = true }
test-case = { workspace = true }
time = { workspace = true, features = ["macros"] }
walkdir = { workspace = true }
