[package]
name = "c8y_http_proxy"
description = "thin-edge Cumulocity extension adding REST API support"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
c8y_api = { workspace = true }
certificate = { workspace = true, features = ["reqwest"] }
download = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
log = { workspace = true }
mqtt_channel = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tedge_actors = { workspace = true }
tedge_config = { workspace = true }
tedge_http_ext = { workspace = true }
tedge_utils = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["formatting"] }
tokio = { workspace = true, features = ["macros"] }

[dev-dependencies]
mockito = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tedge_actors = { workspace = true, features = ["test-helpers"] }
tedge_http_ext = { workspace = true, features = ["test_helpers"] }
tedge_test_utils = { workspace = true }
time = { workspace = true }

[lints]
workspace = true
