input.mqtt.topics = ["te/+/+/+/+/m/+"]

stages = [
    { filter = "add_timestamp.js" },
    { filter = "drop_stragglers.js", config = { max_delay = 60 } },
    { filter = "te_to_c8y.js", meta_topics = ["te/+/+/+/+/m/+/meta"] }
]

output.mqtt.topics = ["c8y/#"]
