[package]
name = "tedge_timer_ext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
tedge_actors = { path = "../../core/tedge_actors" }
tokio = { version = "1.23", default_features = false, features = ["time"] }