[package]
name = "tedge_config"
version = "0.1.0"
authors = ["Software AG <thin-edge-team@softwareag.com>"]
edition = "2018"

[dependencies]
toml = "0.5"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.2"

[dev-dependencies]
assert_matches = "1.4"
