[package]
name = "tedge-watchdog"
description = "tedge-watchdog checks the health of all the thin-edge.io components/services"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
freedesktop_entry_parser = { workspace = true }
futures = { workspace = true }
mqtt_channel = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tedge_api = { workspace = true }
tedge_config = { workspace = true }
tedge_utils = { workspace = true, features = ["logging"] }
thiserror = { workspace = true }
time = { workspace = true, features = ["formatting", "serde-well-known"] }
tokio = { workspace = true, features = ["sync", "time", "rt-multi-thread"] }
tracing = { workspace = true }

[lints]
workspace = true
