[package]
name = "tedge_watchdog"
version = "0.7.0"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.58.1"
license = "Apache-2.0"
description = "tedge_watchdog checks the health of all the thin-edge.io components/services."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.deb]
pre-depends = "tedge"
assets = [
    ["../../../configuration/init/systemd/tedge-watchdog.service", "/lib/systemd/system/tedge-watchdog.service", "644"],
    ["target/release/tedge_watchdog", "/usr/bin/tedge_watchdog", "755"],
]

[dependencies]
anyhow = "1.0"
clap = { version = "3.0", features = ["cargo", "derive"] }
futures = "0.3.21"
mqtt_channel = { path = "../../common/mqtt_channel" }
nanoid = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
freedesktop_entry_parser = "1.3.0"
tedge_config = { path = "../../common/tedge_config" }
tedge_utils = { path = "../../common/tedge_utils", features = ["logging"] }
thiserror ="1.0.30"
time = { version = "0.3", features = ["formatting", "serde-well-known"] }
tokio = { version = "1.12", features = ["sync",  "time", "rt-multi-thread"] }
tracing = { version = "0.1", features = ["attributes", "log"] }
