[package]
name = "thin_edge_json"
version = "0.2.0"
authors = ["Software AG <thin-edge-team@softwareag.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
json = "0.12"
thiserror = "1.0"
clock = {path = "../../common/clock" }
json-writer = {path = "../../common/json_writer" }

[dev-dependencies]
pretty_assertions = "0.7"
proptest = "1.0"
anyhow = "1"
mockall = "0.9"
