[package]
name = "c8y_log_manager"
description = "thin-edge Cumulocity extension adding support for log management"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
c8y_api = { workspace = true }
c8y_http_proxy = { workspace = true }
log = { workspace = true }
log_manager = { workspace = true }
serde = { workspace = true }
tedge_actors = { workspace = true }
tedge_api = { workspace = true }
tedge_config = { workspace = true }
tedge_file_system_ext = { workspace = true }
tedge_mqtt_ext = { workspace = true }
tedge_utils = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros"] }

[dev-dependencies]
filetime = { workspace = true }
tedge_test_utils = { workspace = true }
time = { workspace = true }

[lints]
workspace = true
