[package]
name = "json-writer"
version = "0.7.1"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.58.1"

[dependencies]
serde_json = "1"
thiserror = "1.0"

[dev-dependencies]
anyhow = "1.0"
