[package]
name = "tedge_config_macros"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
camino = { workspace = true, features = ["serde1"] }
doku = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
tedge_config_macros-macro = { path = "macro" }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
serde = { workspace = true, features = ["rc"] }

[lints]
workspace = true
