[package]
name = "tedge_config_macros"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = { version = "*", features = ["serde1"] }
doku = "0.21"
once_cell = "1.17"
serde = "1.0"
tedge_config_macros-macro = { path = "macro" }
thiserror = "1.0"
url = "2.3"

[dev-dependencies]
tracing = "0.1"
