remote_prefix = ""
if = "${config.c8y.mqtt_service.enabled}"

[[rule]]
local_prefix = "${config.c8y.bridge.topic_prefix}/mqtt/out/"
topic = "#"
direction = "outbound"

[[template_rule]]
for = { item = "topic", in = "${config.c8y.mqtt_service.topics}" }
local_prefix = "${config.c8y.bridge.topic_prefix}/mqtt/in/"
topic = "${topic}"
direction = "inbound"