[package]
name = "c8y_api"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = "0.1"
clock = { path = "../../common/clock" }
csv = "1.1"
download = { path = "../../common/download" }
futures = "0.3"
mockall = "0.11"
mqtt_channel = { path = "../../common/mqtt_channel" }
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tedge_api = { path = "../tedge_api" }
tedge_config = { path = "../../common/tedge_config" }
tedge_utils = { path = "../../common/tedge_utils", features = ["logging"] }
thiserror = "1.0"
time = { version = "0.3", features = ["formatting"] }
tokio = { version = "1.23", features = ["rt", "sync", "time"] }
toml = "0.5"
tracing = { version = "0.1", features = ["attributes", "log"] }

[dev-dependencies]
anyhow = "1.0"
assert-json-diff = "2.0"
assert_matches = "1.5"
maplit = "1.0.2"
mockito = "0.31"
regex = "1.7"
tempfile = "3.3"
test-case = "2.2"
time = { version = "0.3", features = ["macros"] }
