[package]
name = "c8y_api"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
camino = { workspace = true }
clock = { workspace = true }
csv = { workspace = true }
download = { workspace = true }
futures = { workspace = true }
mqtt_channel = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls-tls-native-roots"] }
serde = { workspace = true }
serde_json = { workspace = true }
tedge_api = { workspace = true }
tedge_config = { workspace = true }
tedge_utils = { workspace = true, features = ["logging"] }
thiserror = { workspace = true }
time = { workspace = true, features = ["formatting"] }
tokio = { workspace = true, features = ["rt", "sync", "time"] }
toml = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
assert-json-diff = { workspace = true }
assert_matches = { workspace = true }
maplit = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }
time = { workspace = true, features = ["macros"] }

[lints]
workspace = true
