version: '3'
services:
  tedge:
    image: ${DEVCONTAINER_IMAGE:-ghcr.io/thin-edge/devcontainer:latest-trixie}
    environment:
      - DOCKER_HOST=unix:///opt/run/docker.sock

    volumes:
      # Mount docker socket to something other than /var/run as a
      # a privileged container or with CAP_SYS_ADMIN overwrites this
      - /var/run/docker.sock:/opt/run/docker.sock
      - tedge-bashhistory:/commandhistory
      - device-certs:/etc/tedge/device-certs
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ..:/workspace:cached
    privileged: true

volumes:
  tedge-bashhistory:
  device-certs:
