[package]
name = "tedge-agent"
version = "0.8.1"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.63"
license = "Apache-2.0"
description = "tedge-agent interacts with a Cloud Mapper and one or more Software Plugins"
homepage = "https://thin-edge.io"
repository = "https://github.com/thin-edge/thin-edge.io"

[package.metadata.deb]
pre-depends = "tedge-mapper"
replaces = "tedge_agent"
conflicts = "tedge_agent (<= 0.8.1)"
breaks = "tedge_agent (<= 0.8.1)"
provides = "tedge_agent"
maintainer-scripts = "../../../configuration/debian/tedge-agent"
assets = [
    ["../../../configuration/init/systemd/tedge-agent.service", "/lib/systemd/system/tedge-agent.service", "644"],
    ["target/release/tedge-agent", "/usr/bin/tedge-agent", "755"],
]
# Contrary to the other daemons,
# The `agent` does not use `systemd-units` of `cargo-deb`:
# for OTA self-update one needs a fine-control over the deb options

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "3.2", features = ["cargo", "derive"] }
flockfile = { path = "../../common/flockfile" }
futures = "0.3"
futures-util = "0.3"
hyper = { version = "0.14", features = ["full"] }
lazy_static = "1.4"
mqtt_channel = { path = "../../common/mqtt_channel" }
path-clean = "0.1"
plugin_sm = { path = "../plugin_sm" }
routerify = "3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tedge_api = { path = "../../core/tedge_api" }
tedge_config = { path = "../../common/tedge_config" }
tedge_utils = { path = "../../common/tedge_utils", features = ["logging"] }
thiserror = "1.0"
time = { version = "0.3", features = ["formatting"] }
tokio = { version = "1.8", features = ["fs","process", "rt", "rt-multi-thread"] }
toml = "0.5"
tracing = { version = "0.1", features = ["attributes", "log"] }

[dev-dependencies]
anyhow = "1.0"
assert-json-diff = "2.0"
assert_cmd = "2.0"
async-stream = "0.3"
mqtt_tests = { path = "../../tests/mqtt_tests" }
once_cell = "1.8"
predicates = "2.1"
serial_test = "0.8"
tedge_test_utils = { path = "../../tests/tedge_test_utils" }
tedge_utils = { path = "../../common/tedge_utils" }
test-case = "2.2"
tokio-test = "0.4"
toml = "0.5"
