[package]
name = "plugin_sm"
version = "0.4.3"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
csv = "1.1"
download = { path = "../download" }
json_sm = { path = "../json_sm" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tedge_utils = { path = "../../common/tedge_utils" }
thiserror = "1.0"
tokio = { version = "1.8", features = ["process", "rt"] }
tracing = { version = "0.1", features = ["attributes", "log"] }
url = "2.2"

[dev-dependencies]
anyhow = "1.0"
assert_matches = "1.5"
structopt = "0.3"
tempfile = "3.2"
