[package]
name = "certificate"
version = "0.7.3"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.58.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rcgen = { version = "0.9", features = ["pem", "zeroize"] }
sha-1 = "0.10"
thiserror = "1.0"
time = "0.3"
x509-parser = "0.14"
zeroize = "1.5"

[dev-dependencies]
anyhow = "1.0"
assert_matches = "1.5"
base64 = "0.13"
pem = "1.0"
time = {version = "0.3", features = ["macros"]}
