[package]
name = "certificate"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
rcgen = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
sha-1 = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
x509-parser = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
assert_matches = { workspace = true }
base64 = { workspace = true }
pem = { workspace = true }
tempfile = { workspace = true }
time = { workspace = true, features = ["macros"] }

[lints]
workspace = true
