[package]
name = "certificate"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[features]
default = []
reqwest-blocking = ["dep:reqwest", "reqwest/blocking"]
reqwest = ["dep:reqwest"]

[dependencies]
anyhow = { workspace = true }
asn1-rs = { workspace = true }
base64 = "0.22"
camino = { workspace = true }
cryptoki = { workspace = true }
rcgen = { workspace = true }
reqwest = { workspace = true, optional = true, features = [
    "rustls-tls-native-roots",
] }
rustls = { workspace = true }
rustls-native-certs = { workspace = true }
rustls-pemfile = { workspace = true }
sha-1 = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
x509-parser = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
tempfile = { workspace = true }
time = { workspace = true, features = ["macros"] }

[lints]
workspace = true
