[package]
name = "tedge_utils"
description = "tedge_utils provide utilities for thin-edge.io components"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[features]
# No features on by default
default = []
logging = []
fs-notify = ["strum", "notify", "notify-debouncer-full"]
timestamp = ["strum", "time", "serde", "serde_json"]

[dependencies]
anyhow = { workspace = true }
camino = { workspace = true }
doku = { workspace = true }
futures = { workspace = true }
mqtt_channel = { workspace = true }
nix = { workspace = true }
notify = { workspace = true, optional = true }
notify-debouncer-full = { workspace = true, optional = true }
rustls-pemfile = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
strum = { workspace = true, optional = true, features = ["derive"] }
tempfile = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = [
    "formatting",
    "local-offset",
    "parsing",
    "serde",
    "serde-well-known",
], optional = true }
tokio = { workspace = true, default_features = false, features = [
    "fs",
    "io-util",
    "macros",
    "signal",
    "sync",
    "time",
] }
tracing = { workspace = true }
uzers = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
maplit = { workspace = true }
once_cell = { workspace = true }
tedge_test_utils = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
whoami = { workspace = true }

[lints]
workspace = true
