[package]
name = "tedge_utils"
version = "0.7.3"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.58.1"
license = "Apache-2.0"
description = "tedge_utils provide utilities for thin-edge.io components"

[features]
# No features on by default
default = []
logging = ["tracing", "tracing-subscriber"]
fs-notify = ["inotify", "async-stream", "maplit", "strum_macros", "try-traits"]

[dependencies]
anyhow = "1.0"
async-stream = { version = "0.3", optional = true }
futures = "0.3"
inotify = { version = "0.10", optional = true }
maplit = { version = "1.0", optional = true }
nix = "0.24"
strum_macros = { version = "0.24", optional = true }
tempfile = "3.2"
thiserror = "1.0"
tokio = { version = "1.12", default_features = false, features = [ "fs", "io-util", "macros", "signal"] }
tracing = { version = "0.1", features = [], optional = true }
tracing-subscriber = { version = "0.3", optional = true, features = [ "time" ] }
try-traits = { version = "0.1", optional = true }
users = "0.11.0"

[dev-dependencies]
assert_matches = "1.5"
tedge_test_utils = { path = "../../tests/tedge_test_utils" }
tokio = { version = "1.12", features = [ "rt-multi-thread"] }
whoami = "1.2.1"


