[package]
name = "tedge_utils"
version = "0.7.1"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.58.1"
license = "Apache-2.0"
description = "tedge_utils provide utilities for thin-edge.io components"

[features]
# No features on by default
default = []
logging = ["tracing", "tracing-subscriber"]

[dependencies]
anyhow = "1.0"
futures = "0.3"
nix = "0.23.1"
tempfile = "3.2"
thiserror = "1.0"
tokio = { version = "1.12", default_features = false, features = [ "fs", "io-util", "macros", "signal"] }
tracing = { version = "0.1", features = [], optional = true }
tracing-subscriber = { version = "0.3", optional = true, features = [ "time" ] }
users = "0.11.0"

[dev-dependencies]
assert_matches = "1.5"
tokio = { version = "1.12", features = [ "rt-multi-thread"] }
whoami = "1.2.1"


