[package]
name = "thin_edge_json"
version = "0.7.1"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.58.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clock = { path = "../../common/clock", features = ["with-serde"] }
json-writer = { path = "../../common/json_writer" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
thiserror = "1.0"
time = { version = "0.3", features = ["formatting", "local-offset", "parsing", "serde"] }

[dev-dependencies]
anyhow = "1.0"
clock = { path = "../../common/clock" }
criterion = "0.3"
mockall = "0.10"
proptest = "1.0"
stats_alloc = "0.1"
walkdir = "2"
assert_matches = "1.5"
test-case = "2.0"
time = { version = "0.3", features = ["macros"] }

[[bench]]
name = "parsing"
harness = false
