[package]
name = "thin_edge_json"
version = "0.4.3"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
json-writer = { path = "../../common/json_writer" }
serde = "1"
serde_json = "1"
thiserror = "1.0"

[dev-dependencies]
anyhow = "1.0"
clock = { path = "../../common/clock" }
criterion = "0.3"
mockall = "0.10"
proptest = "1.0"
stats_alloc = "0.1"
walkdir = "2"

[[bench]]
name = "parsing"
harness = false
