[package]
name = "tedge_config_manager"
description = "thin-edge extension adding support for configuration management"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
camino = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tedge-write = { workspace = true }
tedge_actors = { workspace = true }
tedge_api = { workspace = true }
tedge_config = { workspace = true }
tedge_downloader_ext = { workspace = true }
tedge_file_system_ext = { workspace = true }
tedge_mqtt_ext = { workspace = true }
tedge_uploader_ext = { workspace = true }
tedge_utils = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
uzers = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
tedge_actors = { workspace = true, features = ["test-helpers"] }
tedge_test_utils = { workspace = true }
tokio = { workspace = true, features = ["macros"] }

[lints]
workspace = true
