[package]
name = "tedge-derive"
version = "0.8.1"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.63"
license = "Apache-2.0"
description = "tedge-derive provides a proc macro for catching unknown fields when deserialising"

[lib]
proc-macro = true

[package.metadata.cargo-udeps.ignore]
normal = ["serde", "toml"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
syn = { version = "1.0", features = [ "full", "extra-traits" ] }
quote = "1.0"
