[package]
name = "download"
description = "download_manager"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
axum_tls = { workspace = true, features = ["error-matching"] }
backoff = { workspace = true }
certificate = { workspace = true, features = ["reqwest"] }
hyper = { workspace = true }
log = { workspace = true }
nix = { workspace = true }
reqwest = { workspace = true, features = ["rustls-tls-native-roots"] }
rustls = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tedge_utils = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
url = { workspace = true }

[dev-dependencies]
mockito = { workspace = true }
regex = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
