[package]
name = "download"
version = "0.5.0"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2018"
license = "Apache-2.0"
description = "download_manager"

[dependencies]
backoff = { version = "0.3", features = ["tokio"] }
json_sm = { path = "../../core/json_sm" }
log = "0.4"
nix = "0.23"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
tedge_utils = { path = "../tedge_utils" }
tempfile = "3.2"
thiserror = "1.0"
tokio = "1.12"
url = "2.2"
libc = "0.2.107"

[dev-dependencies]
anyhow = "1.0"
mockito = "0.30"
regex = "1.5"
tempfile = "3.2"
test-case = "1.2"
tokio-test = "0.4"
