[package]
name = "download"
version = "0.7.3"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.58.1"
license = "Apache-2.0"
description = "download_manager"

[dependencies]
backoff = { version = "0.4", features = ["tokio"] }
log = "0.4"
nix = "0.24"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.12", features = ["fs"] }
url = "2.2"

[dev-dependencies]
anyhow = "1.0"
mockito = "0.31"
regex = "1.5"
tempfile = "3.2"
test-case = "2.0"
tokio-test = "0.4"
