[package]
name = "c8y_config_manager"
description = "thin-edge Cumulocity extension adding support for configuration management"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = { workspace = true }
c8y_api = { workspace = true }
c8y_http_proxy = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tedge_actors = { workspace = true }
tedge_api = { workspace = true }
tedge_config = { workspace = true }
tedge_file_system_ext = { workspace = true }
tedge_mqtt_ext = { workspace = true }
tedge_timer_ext = { workspace = true }
tedge_utils = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
toml = { workspace = true }

[dev-dependencies]
tedge_actors = { workspace = true, features = ["test-helpers"] }
tedge_test_utils = { workspace = true }
tokio = { workspace = true, features = ["time", "test-util"] }
toml = { workspace = true }

[lints]
workspace = true
