[package]
name = "c8y_smartrest"
version = "0.7.2"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.58.1"

[dependencies]
agent_interface = { path = "../agent_interface" }
csv = "1.1"
download = { path = "../../common/download" }
mqtt_channel = { path = "../../common/mqtt_channel" }
json-writer = { path = "../../common/json_writer" }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tedge_config = { path = "../../common/tedge_config" }
thin_edge_json = { path = "../thin_edge_json" }
thiserror = "1.0"
time = { version = "0.3", features = ["formatting", "macros", "parsing", "serde"] }
tokio = { version = "1.8", features = ["rt", "sync", "time"] }
toml = "0.5"
tracing = { version = "0.1", features = ["attributes", "log"] }

[dev-dependencies]
anyhow = "1.0"
assert_matches = "1.5"
assert-json-diff = "2.0"
serde_json = "1.0"
tempfile = "3.3"
test-case = "2.0"
