[package]
name = "c8y_smartrest"
version = "0.5.1"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2018"

[dependencies]
agent_interface = { path = "../agent_interface" }
thin_edge_json = { path = "../thin_edge_json" }
time = { version = "0.3", features = ["macros"] }
chrono = { version = "0.4", features = ["serde"] }
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
assert_matches = "1.5"
assert-json-diff = "2.0"
serde_json = "1.0"
test-case = "1.2.1"
