[package]
name = "c8y_smartrest"
version = "0.4.3"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
csv = "1.1"
json_sm = { path = "../json_sm" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
assert_matches = "1.5"
assert-json-diff = "2.0"
serde_json = "1.0"
test-case = "1.2.1"
