[package]
name = "tedge_mqtt_ext"
description = "thin-edge extension adding MQTT connection"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[features]
# No features on by default
default = []
test-helpers = ["dep:assert-json-diff"]

[dependencies]
assert-json-diff = { workspace = true, optional = true }
async-trait = { workspace = true }
mqtt_channel = { workspace = true }
serde_json = { workspace = true }
tedge_actors = { workspace = true }
tedge_utils = { workspace = true }
tokio = { workspace = true, default_features = false, features = ["macros"] }
tracing = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
mqtt_tests = { path = "../../tests/mqtt_tests" }
proptest = { workspace = true }

[lints]
workspace = true
