[package]
name = "c8y_mapper_ext"
description = "thin-edge Cumulocity extension adding support for Cumulocity data model"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
c8y_api = { workspace = true }
c8y_http_proxy = { workspace = true }
camino = { workspace = true }
clock = { workspace = true }
json-writer = { workspace = true }
mime = { workspace = true }
plugin_sm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tedge_actors = { workspace = true }
tedge_api = { workspace = true }
tedge_config = { workspace = true }
tedge_downloader_ext = { workspace = true }
tedge_file_system_ext = { workspace = true }
tedge_flows = { workspace = true }
tedge_http_ext = { workspace = true }
tedge_mqtt_ext = { workspace = true }
tedge_timer_ext = { workspace = true }
tedge_uploader_ext = { workspace = true }
tedge_utils = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, features = [
    "process",
    "rt",
    "rt-multi-thread",
    "sync",
    "time",
] }
toml = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
assert-json-diff = { workspace = true }
assert_matches = { workspace = true }
mockito = { workspace = true }
proptest = { workspace = true }
tedge_actors = { workspace = true, features = ["test-helpers"] }
tedge_config = { workspace = true, features = ["test"] }
tedge_http_ext = { workspace = true, features = ["test_helpers"] }
tedge_mqtt_ext = { workspace = true, features = ["test-helpers"] }
tedge_test_utils = { workspace = true }
test-case = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
