[package]
name = "log_manager"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
easy_reader = { workspace = true }
glob = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tedge_utils = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["formatting"] }
toml = { workspace = true }

[dev-dependencies]
filetime = { workspace = true }
tedge_test_utils = { workspace = true }
time = { workspace = true, features = ["macros"] }

[lints]
workspace = true
