[package]
name = "c8y_firmware_manager"
description = "Thin-edge device firmware management for Cumulocity"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = { workspace = true }
c8y_api = { workspace = true }
camino = { workspace = true }
log = { workspace = true }
nanoid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha256 = { workspace = true }
tedge_actors = { workspace = true }
tedge_api = { workspace = true }
tedge_config = { workspace = true }
tedge_downloader_ext = { workspace = true }
tedge_mqtt_ext = { workspace = true }
tedge_utils = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
assert-json-diff = { workspace = true }
assert_matches = { workspace = true }
mockall = { workspace = true }
tedge_actors = { workspace = true, features = ["test-helpers"] }
tedge_test_utils = { workspace = true }
tokio = { workspace = true, default_features = false, features = [
    "test-util",
    "rt-multi-thread",
] }

[lints]
workspace = true
