[package]
name = "c8y_auth_proxy"
description = "An HTTP proxy to Cumulocity that automatically authenticates incoming requests"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true, features = ["macros", "ws", "headers"] }
axum-server = { workspace = true }
axum_tls = { workspace = true }
c8y_http_proxy = { workspace = true }
camino = { workspace = true }
futures = { workspace = true }
hyper = { workspace = true }
reqwest = { workspace = true, features = ["stream"] }
rustls = { workspace = true }
tedge_actors = { workspace = true }
tedge_config = { workspace = true }
tedge_config_macros = { workspace = true }
tedge_utils = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
    "process",
    "io-util",
] }
tokio-tungstenite = { workspace = true, features = ["rustls-tls-native-roots"] }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
httparse = { workspace = true }
mockito = { workspace = true }
rcgen = { workspace = true }
rustls = { workspace = true }
tedge_http_ext = { workspace = true, features = ["test_helpers"] }

[lints]
workspace = true
