[package]
name = "clock"
version = "0.7.1"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.58.1"

[dependencies]
mockall = "0.10"
time = "0.3.7"

[features]
default = []
with-serde = ["time/serde-well-known"]
