[package]
name = "clock"
version = "0.8.1"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.63"

[dependencies]
mockall = "0.11"
time = "0.3.7"

[features]
default = []
