[package]
name = "tedge_agent"
version = "0.2.4"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2018"

[package.metadata.deb]
depends = "tedge_mapper"
maintainer-scripts = "configuration/debian/tedge_agent"
assets = [
    ["../../configuration/init/systemd/tedge-agent.service", "/lib/systemd/system/tedge-agent.service", "644"],
    ["target/release/tedge_agent", "/usr/bin/tedge_agent", "755"],
]

[package.metadata.deb.systemd-units]
unit-scripts = "../../configuration/init/systemd"
enable = false
start = false
stop-on-upgrade = false

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
chrono = "0.4"
clock = { path = "../../common/clock" }
env_logger = "0.9"
flockfile = { path = "../../common/flockfile" }
futures = "0.3"
json_sm = { path = "../json_sm" }
log = "0.4"
mockall = "0.10"
mqtt_client = { path = "../../common/mqtt_client" }
plugin_sm = { path = "../plugin_sm" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
tedge_config = { path = "../../tedge_config" }
tedge_utils = { path = "../../common/tedge_utils" }
thiserror = "1.0"
tokio = { version = "1.8", features = ["fs","process", "rt"] }
toml = "0.5"
tracing = { version = "0.1", features = ["attributes", "log"] }
tracing-subscriber = "0.2"

[dev-dependencies]
rumqttd = "0.7"
rumqttlog = "0.7"
once_cell = "1.8"
tempfile = "3.2"
