name: hosted-post-merge_version_update

on:
  workflow_dispatch:
    inputs:
      bump:
        description: Type of version bump
        type: choice
        options:
          - major
          - minor
          - patch
          - release
          - rc
          - beta
          - alpha
        required: true
        default: patch

env:
  CARGO_TERM_COLOR: always

jobs:
  versioning:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          git config --global user.email "info@thin-edge.io"
          git config --global user.name "Versioneer"

      - name: Retrieve MSRV from workspace Cargo.toml
        id: rust_version
        uses: SebRollen/toml-action@v1.0.2
        with:
          file: Cargo.toml
          field: "workspace.package.rust-version"

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable

      - name: Enable cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-release
        run: cargo install --version 0.24.4 cargo-release

      - name: Increment version and tag
        run: cargo release ${{ inputs.bump }} --no-publish --no-push --no-tag -vv --no-confirm --execute

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: ${{ inputs.bump }} version bump
          delete-branch: true
          title: ${{ inputs.bump }} version bump
          body: ${{ inputs.bump }} version bump
          reviewers: rina23q
