name: hosted-post-merge_version_update
on:
  workflow_dispatch:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  versioning:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          git config --global user.email "info@thin-edge.io"
          git config --global user.name "Versioneer"

      - name: enable toolchain via github action
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.51
          components: cargo
          override: true

      - name: Enable cache
        uses: Swatinem/rust-cache@v1

      - name: Install cargo-release
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-release

      - name: Increment version and tag
        uses: actions-rs/cargo@v1
        with:
          command: release
          args: patch --skip-publish --skip-push --skip-tag -vv --no-dev-version --no-confirm

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Patch version bump
          delete-branch: true
          title: Patch version bump
          body: Patch version bump
          reviewers: itsyitsy
