name: postprocess-workflow

on:
  workflow_dispatch:
    branches: [ main, continuous_integration]
  workflow_run:
    workflows: ["system-test-workflow"]
    branches: [main, continuous_integration]
    types:
      - completed
env:
  CARGO_TERM_COLOR: always

jobs:
  postprocess:
    runs-on: [self-hosted, Linux, X64]
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: Call postprocess
      run:  bash  ./ci/postprocess.sh
      env:
            THEGHTOKEN : ${{ secrets.SECRET_THEGHTOKEN  }}
            GOOGLE_APPLICATION_CREDENTIALS : ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
