name: system-test-workflow-2

on:

  workflow_dispatch:
    branches: [ main, continuous_integration]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: [self-hosted, Linux, ARM]

    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: Run all Tests
      run:  bash  ./ci/ci_run_all_tests_2.sh
      env:
            C8YPASS: ${{ secrets.SECRET_C8YPASS }}
            C8YUSERNAME: ${{ secrets.SECRET_C8YUSERNAME }}
            C8YTENNANT: ${{secrets.SECRET_C8YTENANT}}
            C8YDEVICE: ${{ secrets.SECRET_C8YDEVICE }}
            C8YTENANT: ${{secrets.SECRET_C8YTENANT}}
            C8YDEVICEID: ${{ secrets.SECRET_C8YDEVICEID }}
            TIMEZONE: 01:00
            TEBASEDIR: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/
            EXAMPLEDIR: /home/pi

