name: system-test-workflow

on:

  workflow_dispatch:
    branches: [ main, continuous_integration]
  workflow_run:
    workflows: ["integration-test-workflow"]
    branches: [main, continuous_integration]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  system-test:
    runs-on: [self-hosted, Linux, ARM]
    # wtf if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: Run all Tests
      run:  bash  ./ci/ci_run_all_tests.sh
      env:
            C8YPASS: ${{ secrets.SECRET_C8YPASS }}
            C8YUSERNAME: ${{ secrets.SECRET_C8YUSERNAME }}
            C8YTENNANT: ${{secrets.SECRET_C8YTENANT}}
            C8YDEVICE: ${{ secrets.SECRET_C8YDEVICE }}
            C8YTENANT: ${{secrets.SECRET_C8YTENANT}}
            C8YDEVICEID: ${{ secrets.SECRET_C8YDEVICEID }}
            TIMEZONE: 01:00
            TEBASEDIR: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/
            EXAMPLEDIR: /home/pi
            RUN_NUMBER: ${{ github.run_number }}
    - name: upload results as zip
      # https://github.com/marketplace/actions/upload-a-build-artifact
      uses: actions/upload-artifact@v2
      with:
        name: results_$RUN_NUMBER
        path: tests/
